controller:
  serviceType: LoadBalancer

  numExecutors: 0

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - github
    - configuration-as-code
    - azure-credentials

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

    limits:
      cpu: "2"
      memory: 4Gi

agent:
  enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi

    limits:
      cpu: "1"
      memory: 1Gi

persistence:
  enabled: true
  storageClass: managed-csi
  size: 20Gi